#pragma once
#include <lvgl.h>

/**
 * Noto Sans KR 16px — Korean syllables (가-힣), IPS10 only (see the .c wrapper).
 * Fallback face for font_kr_16 / font_kr_20 so Korean card text on the 10"
 * 1280×800 panel renders at a legible size instead of dropping to the 12px
 * face (the old chain made every 한글 summary line ~2mm tall and blurry).
 * Generated by lv_font_conv, BPP 4.
 */
LV_FONT_DECLARE(font_noto_kr_16);
